# Generated by Django 4.1 on 2022-09-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlobby', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='online',
        ),
    ]
