# Generated by Django 4.1 on 2022-10-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlobby', '0005_delete_username_alter_room_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='online',
            field=models.ManyToManyField(blank=True, to='watchlobby.username'),
        ),
    ]
