# Generated by Django 4.1 on 2022-10-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlobby', '0006_username_alter_room_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='room_connected',
            field=models.ManyToManyField(blank=True, to='watchlobby.room'),
        ),
    ]
