# Generated by Django 4.1 on 2022-10-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlobby', '0008_alter_room_current_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_vid',
            field=models.CharField(blank=True, default='MBzi6hRrkww', max_length=256, null=True),
        ),
    ]
