# Generated by Django 4.1 on 2022-10-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlobby', '0009_alter_room_current_vid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='online',
        ),
        migrations.DeleteModel(
            name='Username',
        ),
    ]
